/* eslint-disable no-console */
/**
 * Load the printed book codes into the database.
 *
 * The codes inside the books were not generated by this system. They arrived
 * as a 3,000-line PDF, numbered 1..3000, in a format this system does not
 * produce — `00N2-EB6V-05VX-9XM1`, no prefix, using every character
 * generateCode() deliberately avoids. Those are the real codes. Until they are
 * in the database, a buyer typing the code from their own book is told it does
 * not exist.
 *
 * THE SERIAL IS THE POINT, not decoration. The codes are unordered by design —
 * one must give away nothing about another — so the sheet's numbering is the
 * only handle the shop has on "the first five hundred books". It is read from
 * the sheet's own order and stored, so "release codes up to 500" stays
 * answerable later.
 *
 * WHAT IT WILL NOT DO
 *   - never overwrite a code that is already there (a redeemed one especially)
 *   - never delete anything; retiring the old MV- codes is a separate decision
 *   - never run without --apply
 *
 * Dry run by default:
 *   npx ts-node --transpile-only src/scripts/importPrintedCodes.ts "../Magic viva Book Code.pdf"
 *   npx ts-node --transpile-only src/scripts/importPrintedCodes.ts "../Magic viva Book Code.pdf" --apply
 */
import path from 'path';
import mongoose from 'mongoose';
import { createRequire } from 'module';

const BATCH = 'PRINT-2026-09-PDF';

/** Four groups of four, exactly as the sheet prints them. */
const CODE_RE = /\b[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}\b/g;

/**
 * Every code in the PDF, in the order it is printed.
 *
 * The sheet writes the number AFTER the code it labels ("00N2-… 1. 00WM-… 2."),
 * so pairing on the visible number would shift every code by one. The nth code
 * on the sheet is book n; that is what the reading order gives, and that is
 * what is used.
 */
const readPdf = async (file: string): Promise<string[]> => {
  const req = createRequire(path.join(process.cwd(), '../sabbirbooks/package.json'));
  const pdfjs = req('pdfjs-dist/legacy/build/pdf.mjs');
  const doc = await pdfjs.getDocument({ url: file, useSystemFonts: true }).promise;

  const codes: string[] = [];
  for (let p = 1; p <= doc.numPages; p++) {
    const page = await doc.getPage(p);
    const content = await page.getTextContent();
    const text = content.items.map((i: { str: string }) => i.str).join(' ');
    for (const match of text.matchAll(CODE_RE)) codes.push(match[0].toUpperCase());
  }
  return codes;
};

(async () => {
  const apply = process.argv.includes('--apply');
  const file = process.argv[2];
  if (!file || file.startsWith('--')) {
    console.error('Pass the PDF path as the first argument.');
    process.exit(1);
  }

  const codes = await readPdf(path.resolve(file));
  const unique = new Set(codes);
  console.log(`\nRead ${codes.length} codes from the sheet, ${unique.size} of them distinct.`);
  if (codes.length !== unique.size) {
    // Two books carrying one code is unfixable after printing, so it stops here
    // rather than importing a set that cannot be trusted.
    console.error('❌ The sheet repeats a code. Refusing to import.');
    process.exit(1);
  }

  await import('../app/config');
  const { dbConnect } = await import('../app/utils/dbConnect');
  await dbConnect();

  const { BookCopy } = await import('../app/modules/bookCopy/bookCopy.model');
  const { Book } = await import('../app/modules/book/book.model');

  // The codes are for one title. Picking it by name rather than by "the only
  // book" so a second title later cannot silently absorb this batch.
  const book: { _id: unknown; title?: string } | null = await Book.findOne({
    title: /MAGIC VIVA ANATOMY/i,
  })
    .select('title')
    .lean();
  if (!book) {
    console.error('❌ Could not find the book "MAGIC VIVA ANATOMY".');
    process.exit(1);
  }
  console.log(`Book: ${book.title}`);

  const existing = await BookCopy.find({ code: { $in: [...unique] } })
    .select('code status serial')
    .lean();
  const already = new Map(existing.map((d) => [String(d.code), d]));
  const toInsert = codes
    .map((code, i) => ({ code, serial: i + 1 }))
    .filter((row) => !already.has(row.code));

  console.log(`\nAlready in the database : ${already.size}`);
  console.log(`To insert               : ${toInsert.length}`);
  if (already.size > 0) {
    const redeemed = existing.filter((d) => d.status === 'redeemed').length;
    console.log(`  (of those, redeemed: ${redeemed} — never touched)`);
  }

  if (toInsert.length > 0) {
    console.log('\nFirst three and last three:');
    for (const row of [...toInsert.slice(0, 3), ...toInsert.slice(-3)]) {
      console.log(`  #${String(row.serial).padStart(4)}  ${row.code}`);
    }
  }

  if (!apply) {
    console.log('\n── DRY RUN — nothing written. Re-run with --apply to commit. ──\n');
    await mongoose.disconnect();
    process.exit(0);
  }

  console.log('\n── APPLYING ──');
  // Chunked: one 3,000-document insert is a single oversized round trip, and a
  // failure halfway through it says nothing about what landed. ordered:false so
  // one bad row cannot abandon the rest of its chunk.
  const CHUNK = 500;
  let inserted = 0;
  for (let i = 0; i < toInsert.length; i += CHUNK) {
    const slice = toInsert.slice(i, i + CHUNK).map((row) => ({
      ...row,
      book: book._id,
      batch: BATCH,
      status: 'available' as const,
    }));
    const res = await BookCopy.insertMany(slice, { ordered: false });
    inserted += res.length;
    console.log(`  ${inserted} / ${toInsert.length}`);
  }

  const total = await BookCopy.countDocuments({ batch: BATCH });
  console.log(`\n✅ ${inserted} inserted. Batch "${BATCH}" now holds ${total}.`);

  // Read back the two ends, because "3000 inserted" and "the serials are right"
  // are different claims and only the second one matters later.
  const first = await BookCopy.findOne({ batch: BATCH, serial: 1 }).select('code serial').lean();
  const last = await BookCopy.findOne({ batch: BATCH, serial: codes.length })
    .select('code serial')
    .lean();
  console.log(`   #1    ${first?.code}   (sheet: ${codes[0]})`);
  console.log(`   #${codes.length}  ${last?.code}   (sheet: ${codes[codes.length - 1]})`);

  await mongoose.disconnect();
  process.exit(0);
})().catch((e) => {
  console.error('❌ Failed:', e);
  process.exit(1);
});
