/* eslint-disable no-console */
/**
 * Delete the codes that are not in any book.
 *
 * 1,000 codes were generated by this system on 3 September, before the printed
 * sheet arrived. Nothing was ever printed with them. The 3,000 real codes came
 * later as a PDF, and since both sets sit in the same collection the admin's
 * "চালু আছে" tab counts 1,498 usable codes when 500 books exist — a number the
 * shop cannot plan a print run against.
 *
 * So the unprinted set goes. It is identified by BATCH, not by shape: deleting
 * "everything that does not look like the new format" would be a rule that
 * quietly widens the day somebody imports a differently-shaped sheet.
 *
 * TWO OF THEM WERE REDEEMED, and that is the part worth understanding before
 * running this. Deleting those rows does NOT take the book away from either
 * reader — access lives in `bookaccesses`, granted at redemption and keyed on
 * the person and the book, not on the code. The script proves that rather than
 * asserting it: it counts their grants before and after and refuses to finish
 * quietly if the number moved.
 *
 * Dry run by default:
 *   npx ts-node --transpile-only src/scripts/removeNonPrintedCodes.ts
 *   npx ts-node --transpile-only src/scripts/removeNonPrintedCodes.ts --apply
 */
import mongoose from 'mongoose';

/** The run this system generated. The printed sheet is PRINT-2026-09-PDF. */
const DOOMED_BATCH = 'PRINT-2026-09';
const KEEP_BATCH = 'PRINT-2026-09-PDF';

(async () => {
  const apply = process.argv.includes('--apply');

  await import('../app/config');
  const { dbConnect } = await import('../app/utils/dbConnect');
  await dbConnect();

  const { BookCopy } = await import('../app/modules/bookCopy/bookCopy.model');
  const { BookAccess } = await import('../app/modules/bookAccess/bookAccess.model');

  const doomed = await BookCopy.find({ batch: DOOMED_BATCH })
    .select('code status redeemedBy book')
    .lean();
  const keeping = await BookCopy.countDocuments({ batch: KEEP_BATCH });
  const redeemed = doomed.filter((c) => c.status === 'redeemed');

  console.log(apply ? '\n── APPLYING ──\n' : '\n── DRY RUN ──\n');
  console.log(`Keeping  "${KEEP_BATCH}" : ${keeping}`);
  console.log(`Deleting "${DOOMED_BATCH}"     : ${doomed.length}`);
  console.log(`  of those, already redeemed : ${redeemed.length}`);

  if (doomed.length === 0) {
    console.log('\nNothing to do.');
    await mongoose.disconnect();
    process.exit(0);
  }

  // The readers whose codes are about to disappear, and whether they hold the
  // book right now. Measured before, compared after — the one thing that must
  // not change.
  const before: { code: string; user: string; book: string; has: boolean }[] = [];
  for (const c of redeemed) {
    const grant = await BookAccess.findOne({
      userId: c.redeemedBy,
      bookId: c.book,
      revokedAt: { $exists: false },
    }).lean();
    before.push({
      code: String(c.code),
      user: String(c.redeemedBy),
      book: String(c.book),
      has: Boolean(grant),
    });
  }

  if (before.length) {
    console.log('\nReaders holding one of these codes:');
    before.forEach((b) => console.log(`  ${b.code}  access now: ${b.has ? 'yes' : 'NO'}`));
    console.log(
      '\n  Their access is granted on (reader, book) and does not read the code,\n' +
        '  so deleting the row should leave every "yes" above unchanged.'
    );
  }

  if (!apply) {
    console.log('\n── Nothing written. Re-run with --apply to commit. ──\n');
    await mongoose.disconnect();
    process.exit(0);
  }

  const res = await BookCopy.deleteMany({ batch: DOOMED_BATCH });
  console.log(`\n🗑  ${res.deletedCount} deleted.`);

  // Prove it, rather than promise it.
  let lost = 0;
  for (const b of before) {
    const grant = await BookAccess.findOne({
      userId: b.user,
      bookId: b.book,
      revokedAt: { $exists: false },
    }).lean();
    const has = Boolean(grant);
    console.log(`  ${b.code}  access after: ${has ? 'yes' : 'NO'}${has === b.has ? '' : '  ← CHANGED'}`);
    if (b.has && !has) lost += 1;
  }
  if (lost > 0) {
    console.error(`\n❌ ${lost} reader(s) lost access. Investigate before doing anything else.`);
    await mongoose.disconnect();
    process.exit(1);
  }

  const total = await BookCopy.countDocuments({});
  const live = await BookCopy.countDocuments({ status: 'available', released: { $ne: false } });
  console.log(`\n✅ Codes remaining: ${total}   ready to use: ${live}`);

  await mongoose.disconnect();
  process.exit(0);
})().catch((e) => {
  console.error('❌ Failed:', e);
  process.exit(1);
});
